### ISSUE TITLE
(...)

### ISSUE THREAD

**Issue by enigma-watcher** [VitorSavedra/consulta-massa-placa-sinesp#1]
![screenshot_20180813-101320_sinesp cidadao](https://user-images.githubusercontent.com/42346260/44037466-cfd38c98-9eea-11e8-90ef-71a2106bf14e.jpg)

**Comment by VitorSavedra** [comment]
O projeto não trata-se da divulgação, comercialização e ou transmissão a terceiros de dados do DENATRAN, mas sim, de um script/ferramenta aberta que possibilita  a consulta em seu banco de dados. No demais, as informações são públicas e a utilização é de responsabilidade do executor.
